# Generated by Django 4.1.2 on 2022-10-10 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_order_product_shippingaddress_ordered_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordered_product',
            name='order',
        ),
        migrations.RemoveField(
            model_name='ordered_product',
            name='product',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='ordered_product',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
