# Generated by Django 4.1.2 on 2022-10-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='identification',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
