# Generated by Django 4.1.2 on 2022-10-10 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_order_identification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ordered_product',
            new_name='orderedproduct',
        ),
        migrations.RenameField(
            model_name='orderedproduct',
            old_name='sold_sinc',
            new_name='sold_since',
        ),
    ]
