# Generated by Django 4.1.2 on 2022-10-10 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_ordered_product_orderedproduct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopuser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='shopuser',
            name='password',
        ),
    ]
