# Generated by Django 4.1.2 on 2022-11-07 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_order_customer_alter_shippingaddress_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='identification',
            new_name='transaction_id',
        ),
    ]
